import Link from "next/link";
import { CampaignCard } from "@/components/campaigns/CampaignCard";
import { Stat } from "@/components/common/Stat";
import { HomeExperience } from "@/components/home/HomeExperience";
import { RecentDonations } from "@/components/donation/RecentDonations";
import { TopDonors } from "@/components/donation/TopDonors";
import { campaigns } from "@/data/campaigns";
import { donations, getTopDonors } from "@/data/donations";
import { findParticipantBySlug } from "@/data/participants";
const numberFormatter = new Intl.NumberFormat("es-AR");
export default async function Home({ searchParams }: { searchParams: Promise<{ participant?: string }> }) { const { participant: slug } = await searchParams; const initialParticipant = slug ? findParticipantBySlug(slug) : undefined; return <main>
  <section className="mx-auto max-w-6xl px-5 pb-20 pt-24 text-center sm:px-8 sm:pt-32"><div className="mx-auto mb-8 flex w-fit items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/[0.06] px-4 py-2 text-xs font-bold uppercase tracking-[0.15em] text-emerald-300"><span className="size-2 animate-pulse rounded-full bg-emerald-400" />Ranking de impacto</div><h1 className="mx-auto max-w-4xl font-display text-5xl font-black uppercase leading-[0.94] tracking-[-0.05em] text-white sm:text-7xl lg:text-8xl">¿Quién plantó más <span className="text-emerald-400">árboles?</span></h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">Comunidades, streamers y creadores compiten para plantar árboles. Cada aporte suma al ranking y convierte la rivalidad en impacto colectivo.</p><div className="mx-auto mt-12 flex w-fit max-w-full divide-x divide-white/10 rounded-2xl border border-white/8 bg-white/[0.025] px-1 py-5"><div className="px-4 sm:px-10"><Stat value={numberFormatter.format(18_421)} label="árboles" /></div><div className="px-4 sm:px-10"><Stat value={numberFormatter.format(9_431)} label="personas participaron" /></div></div></section>
  <HomeExperience initialParticipant={initialParticipant} />
  <section className="mx-auto grid max-w-6xl gap-8 px-5 pb-20 sm:px-8 md:grid-cols-2"><RecentDonations donations={donations} /><TopDonors donors={getTopDonors(donations)} /></section>
  <section className="mx-auto max-w-6xl px-5 py-20 sm:px-8 sm:py-28"><div className="mb-9 flex items-end justify-between gap-5"><div><p className="eyebrow">Transparencia operativa</p><h2 className="mt-3 font-display text-3xl font-bold uppercase text-white sm:text-4xl">Últimas novedades</h2></div><Link href="/novedades" className="hidden text-sm font-bold text-emerald-300 sm:block">Ver todas →</Link></div><div className="grid gap-4 md:grid-cols-3">{campaigns.slice(0, 3).map((campaign) => <CampaignCard key={campaign.id} campaign={campaign} />)}</div><Link href="/novedades" className="mt-6 inline-block text-sm font-bold text-emerald-300 sm:hidden">Ver todas las novedades →</Link></section>
  <section className="border-y border-white/8 bg-white/[0.018]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 sm:px-8 md:grid-cols-3"><div><p className="eyebrow">Cómo funciona</p><h2 className="mt-3 font-display text-3xl font-bold uppercase text-white">Una métrica clara</h2></div><div><p className="text-4xl font-black text-emerald-400">01</p><h3 className="mt-4 font-bold text-white">Elegís a quién apoyar</h3><p className="mt-2 text-sm leading-6 text-zinc-500">Seleccionás una comunidad o hacés una donación general.</p></div><div><p className="text-4xl font-black text-emerald-400">02</p><h3 className="mt-4 font-bold text-white">El ranking se mueve</h3><p className="mt-2 text-sm leading-6 text-zinc-500">Cada árbol confirmado suma al total público del participante.</p></div></div></section>
</main>; }
