"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireAdmin } from "@/lib/admin/auth";
import { createAuthSupabaseClient } from "@/lib/supabase/auth-server";
import { createServiceRoleSupabaseClient } from "@/lib/supabase/server";
import { bool, campaignStatus, dateValue, evidenceType, integer, nullablePostgresUuid, slugValue, text, urlValue, uuid } from "@/lib/admin/validation";

const ok = (path: string, message: string) => redirect(`${path}?message=${encodeURIComponent(message)}`);
const fail = (path: string, error: unknown) => redirect(`${path}?error=${encodeURIComponent(error instanceof Error ? error.message : "Error inesperado.")}`);
function audit(userId: string, action: string, entity: string, entityId: string) { console.info("[Admin]", { userId, action, entity, entityId }); }

export async function loginAction(form: FormData) {
  const email = String(form.get("email") ?? "").trim(), password = String(form.get("password") ?? "");
  if (!email || !password) redirect("/admin/login?error=Completá email y contraseña.");
  const auth = await createAuthSupabaseClient();
  const result = await auth.auth.signInWithPassword({ email, password });
  if (result.error || !result.data.user) redirect("/admin/login?error=Credenciales inválidas.");
  const { data } = await createServiceRoleSupabaseClient().from("admin_users").select("user_id").eq("user_id", result.data.user.id).maybeSingle();
  if (!data) { await auth.auth.signOut(); redirect("/admin/login?error=No tenés permisos de administración."); }
  redirect("/admin");
}
export async function logoutAction() { const auth = await createAuthSupabaseClient(); await auth.auth.signOut(); redirect("/admin/login"); }

function participantPayload(form: FormData) { return { name: text(form, "name", true, 120)!, slug: slugValue(form), category_id: nullablePostgresUuid(form, "category_id", "categoría"), avatar_url: urlValue(form, "avatar_url"), active: bool(form, "active") }; }
export async function createParticipantAction(form: FormData) {
  const admin = await requireAdmin();
  try { const payload = participantPayload(form); const db = createServiceRoleSupabaseClient(); if (payload.category_id && !(await db.from("categories").select("id").eq("id", payload.category_id).maybeSingle()).data) throw new Error("categoría inválida."); const { data, error } = await db.from("participants").insert(payload).select("id").single(); if (error) throw new Error(error.code === "23505" ? "El slug ya existe." : "No se pudo crear el participante."); audit(admin.userId, "create", "participant", data.id); revalidatePath("/admin/participantes"); ok("/admin/participantes", "Participante creado."); } catch (error) { fail("/admin/participantes", error); }
}
export async function updateParticipantAction(id: string, form: FormData) {
  const admin = await requireAdmin(); const safeId = uuid(id);
  try { const payload = participantPayload(form); const db = createServiceRoleSupabaseClient(); if (payload.category_id && !(await db.from("categories").select("id").eq("id", payload.category_id).maybeSingle()).data) throw new Error("categoría inválida."); const { error } = await db.from("participants").update(payload).eq("id", safeId); if (error) throw new Error(error.code === "23505" ? "El slug ya existe." : "No se pudo guardar."); audit(admin.userId, "update", "participant", safeId); revalidatePath("/admin/participantes"); ok(`/admin/participantes/${safeId}`, "Cambios guardados."); } catch (error) { fail(`/admin/participantes/${safeId}`, error); }
}
export async function toggleParticipantAction(id: string, active: boolean) { const admin = await requireAdmin(); const safeId = uuid(id); const { error } = await createServiceRoleSupabaseClient().from("participants").update({ active }).eq("id", safeId); if (error) fail("/admin/participantes", new Error("No se pudo cambiar el estado.")); audit(admin.userId, active ? "activate" : "deactivate", "participant", safeId); revalidatePath("/admin/participantes"); ok("/admin/participantes", active ? "Participante activado." : "Participante desactivado."); }

function campaignPayload(form: FormData) { return { title: text(form, "title", true, 180)!, slug: slugValue(form), ngo_name: text(form, "ngo_name", false, 180), location: text(form, "location", false, 180), impact_goal: integer(form, "impact_goal"), goal_amount: integer(form, "goal_amount"), status: campaignStatus(String(form.get("status") ?? "")), activity_date: dateValue(form, "activity_date"), delivery_date: dateValue(form, "delivery_date"), excerpt: text(form, "excerpt", false, 500), description: text(form, "description", true, 10000), cover_image_url: urlValue(form, "cover_image_url") }; }
export async function createCampaignAction(form: FormData) { const admin = await requireAdmin(); try { const { data, error } = await createServiceRoleSupabaseClient().from("campaigns").insert({ ...campaignPayload(form), published_at: bool(form, "published") ? new Date().toISOString() : null }).select("id").single(); if (error) throw new Error(error.code === "23505" ? "El slug ya existe." : "No se pudo crear la campaña."); audit(admin.userId, "create", "campaign", data.id); revalidatePath("/admin/campanas"); ok(`/admin/campanas/${data.id}`, "Campaña creada."); } catch (error) { fail("/admin/campanas", error); } }
export async function updateCampaignAction(id: string, form: FormData) { const admin = await requireAdmin(); const safeId = uuid(id); try { const { error } = await createServiceRoleSupabaseClient().from("campaigns").update(campaignPayload(form)).eq("id", safeId); if (error) throw new Error(error.code === "23505" ? "El slug ya existe." : "No se pudo guardar."); audit(admin.userId, "update", "campaign", safeId); revalidatePath("/admin/campanas"); ok(`/admin/campanas/${safeId}`, "Cambios guardados."); } catch (error) { fail(`/admin/campanas/${safeId}`, error); } }
export async function toggleCampaignPublishAction(id: string, publish: boolean) { const admin = await requireAdmin(); const safeId = uuid(id); const { error } = await createServiceRoleSupabaseClient().from("campaigns").update({ published_at: publish ? new Date().toISOString() : null }).eq("id", safeId); if (error) fail("/admin/campanas", new Error("No se pudo cambiar la publicación.")); audit(admin.userId, publish ? "publish" : "unpublish", "campaign", safeId); revalidatePath("/admin/campanas"); ok("/admin/campanas", publish ? "Campaña publicada." : "Campaña despublicada."); }

export async function saveUpdateAction(campaignId: string, updateId: string | null, form: FormData) { const admin = await requireAdmin(); const cid = uuid(campaignId, "campaign_id"); try { const payload = { campaign_id: cid, title: text(form, "title", true, 180)!, content: text(form, "content", false, 5000), event_date: dateValue(form, "event_date") || (() => { throw new Error("event_date: campo requerido."); })() }; const db = createServiceRoleSupabaseClient(); const result = updateId ? await db.from("campaign_updates").update(payload).eq("id", uuid(updateId)).select("id").single() : await db.from("campaign_updates").insert(payload).select("id").single(); if (result.error) throw new Error("No se pudo guardar la actualización."); audit(admin.userId, updateId ? "update" : "create", "campaign_update", result.data.id); revalidatePath(`/admin/campanas/${cid}`); ok(`/admin/campanas/${cid}`, "Actualización guardada."); } catch (error) { fail(`/admin/campanas/${cid}`, error); } }
export async function deleteUpdateAction(campaignId: string, id: string) { const admin = await requireAdmin(); const cid = uuid(campaignId), safeId = uuid(id); const { error } = await createServiceRoleSupabaseClient().from("campaign_updates").delete().eq("id", safeId).eq("campaign_id", cid); if (error) fail(`/admin/campanas/${cid}`, new Error("No se pudo eliminar.")); audit(admin.userId, "delete", "campaign_update", safeId); revalidatePath(`/admin/campanas/${cid}`); ok(`/admin/campanas/${cid}`, "Actualización eliminada."); }
export async function saveEvidenceAction(campaignId: string, evidenceId: string | null, form: FormData) { const admin = await requireAdmin(); const cid = uuid(campaignId); try { const payload = { campaign_id: cid, type: evidenceType(String(form.get("type") ?? "")), label: text(form, "label", true, 240)!, url: urlValue(form, "url"), evidence_date: dateValue(form, "evidence_date") }; const db = createServiceRoleSupabaseClient(); const result = evidenceId ? await db.from("campaign_evidence").update(payload).eq("id", uuid(evidenceId)).select("id").single() : await db.from("campaign_evidence").insert(payload).select("id").single(); if (result.error) throw new Error("No se pudo guardar la evidencia."); audit(admin.userId, evidenceId ? "update" : "create", "campaign_evidence", result.data.id); revalidatePath(`/admin/campanas/${cid}`); ok(`/admin/campanas/${cid}`, "Evidencia guardada."); } catch (error) { fail(`/admin/campanas/${cid}`, error); } }
export async function deleteEvidenceAction(campaignId: string, id: string) { const admin = await requireAdmin(); const cid = uuid(campaignId), safeId = uuid(id); const { error } = await createServiceRoleSupabaseClient().from("campaign_evidence").delete().eq("id", safeId).eq("campaign_id", cid); if (error) fail(`/admin/campanas/${cid}`, new Error("No se pudo eliminar.")); audit(admin.userId, "delete", "campaign_evidence", safeId); revalidatePath(`/admin/campanas/${cid}`); ok(`/admin/campanas/${cid}`, "Evidencia eliminada."); }
