import Link from "next/link";
import { notFound } from "next/navigation";
import { RecentDonations } from "@/components/donation/RecentDonations";
import { TopDonors } from "@/components/donation/TopDonors";
import { donations, getTopDonors } from "@/data/donations";
import { findParticipantBySlug, rankingParticipants } from "@/data/participants";
import { calculateTreesToNextPosition } from "@/lib/ranking";
const nf = new Intl.NumberFormat("es-AR");
export default async function Page({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const participant = findParticipantBySlug(slug); if (!participant) notFound(); const gap = calculateTreesToNextPosition(participant, rankingParticipants); const previous = rankingParticipants.find((item) => item.position === participant.position - 1); const participantDonations = donations.filter((donation) => donation.participantSlug === participant.slug); return <main className="mx-auto max-w-6xl px-5 py-20 sm:px-8"><section className="grid gap-8 rounded-[2rem] border border-white/9 bg-white/[0.03] p-6 sm:p-10 md:grid-cols-[auto_1fr_auto] md:items-center"><div className="grid size-24 place-items-center rounded-3xl border border-emerald-400/20 bg-emerald-400/10 text-2xl font-bold text-emerald-300" aria-label={`Avatar de ${participant.name}`}>{participant.initials}</div><div><p className="text-sm uppercase tracking-wider text-zinc-500">#{participant.position} del ranking · {participant.category}</p><h1 className="mt-2 font-display text-4xl font-black uppercase text-white sm:text-6xl">{participant.name} {participant.verified && <span className="text-sky-400">✓</span>}</h1><p className="mt-4 max-w-2xl text-zinc-400">{participant.description}</p><div className="mt-6 flex flex-wrap gap-6"><p><strong className="text-2xl text-white">{nf.format(participant.treesFunded)}</strong><br/><span className="text-xs text-zinc-500">árboles</span></p><p><strong className="text-2xl text-white">{nf.format(participant.contributors)}</strong><br/><span className="text-xs text-zinc-500">donantes</span></p><p><strong className="text-2xl text-emerald-300">+{nf.format(participant.recentTrees)}</strong><br/><span className="text-xs text-zinc-500">esta semana</span></p></div><p className="mt-5 text-sm text-zinc-300">{gap === null ? "Lidera el ranking." : `Faltan ${nf.format(gap)} árboles para superar a ${previous?.name}.`}</p></div><Link href={`/?participant=${participant.slug}#donar`} className="rounded-full bg-emerald-400 px-5 py-4 text-center text-xs font-bold uppercase text-emerald-950">Plantar por {participant.name.split(" ")[0]}</Link></section><div className="mt-12 grid gap-8 md:grid-cols-2"><RecentDonations donations={participantDonations} /><TopDonors donors={getTopDonors(participantDonations)} /></div></main>; }
